
# Database Configuration
server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost/bob
    username: root
    password: 1234
    driver-class-name : com.mysql.cj.jdbc.Driver

  main:
    web-application-type=none:
    allow-circular-references: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


